# docker build -t reducible/centosdev:5 -f Dockerfile.el5 .
FROM centos:5

RUN yum clean all
RUN yum -y upgrade
RUN yum -y groupinstall "Development tools"  
RUN yum -y install openssl-devel pcre-devel zlib-devel readline-devel libtermcap-devel wget curl