# docker build -t el5dev -f Dockerfile.el5 .
# docker run -t -i -v $PWD:/vagrant el5dev /vagrant/build.sh
FROM centos:5

RUN yum clean all
RUN yum -y groupinstall "Development tools"  
RUN yum -y install openssl-devel pcre-devel zlib-devel readline-devel libtermcap-devel wget curl
