# docker build -t reducible/centosdev:5 -f Dockerfile.el5 .
# docker run -t -i -v $PWD:/vagrant centosdev:5 /vagrant/build.sh
FROM centos:5

RUN yum clean all
RUN yum -y upgrade
RUN yum -y groupinstall "Development tools"  
RUN yum -y install openssl-devel pcre-devel zlib-devel readline-devel libtermcap-devel wget curl